# Generated by Django 5.1.1 on 2024-10-29 09:20

import home_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', validators=[home_app.models.validate_image_blog]),
        ),
    ]
