# Generated by Django 5.1.1 on 2024-10-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressHeaderImage',
            fields=[
                ('headerimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_app.headerimage')),
            ],
            bases=('home_app.headerimage',),
        ),
        migrations.CreateModel(
            name='AddressSidebarNews',
            fields=[
                ('sidebarnews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_app.sidebarnews')),
            ],
            bases=('home_app.sidebarnews',),
        ),
    ]
