# Generated by Django 5.1.1 on 2024-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
