# Generated by Django 5.1.1 on 2024-10-29 08:26

import tattoo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterimage',
            name='image',
            field=models.ImageField(upload_to='master_images/', validators=[tattoo_app.models.validate_image_gallery]),
        ),
        migrations.AlterField(
            model_name='tattooimage',
            name='image',
            field=models.ImageField(upload_to='tattoo_images/', validators=[tattoo_app.models.validate_image_gallery]),
        ),
    ]
