# Generated by Django 5.1.1 on 2024-10-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0003_tattooheaderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='image_url',
        ),
        migrations.CreateModel(
            name='MasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tattoo_app.master')),
            ],
        ),
        migrations.CreateModel(
            name='TattooImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tattoo_app.tattoo')),
            ],
        ),
    ]
