# Generated by Django 5.1.1 on 2024-10-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0004_remove_master_image_url_remove_tattoo_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterimage',
            name='image',
            field=models.ImageField(upload_to='master_images/'),
        ),
        migrations.AlterField(
            model_name='tattooimage',
            name='image',
            field=models.ImageField(upload_to='tattoo_images/'),
        ),
    ]
