# Generated by Django 5.1.1 on 2024-10-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='tattoo_app.category'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='tattoo_app.category'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='tattoo_app.master'),
        ),
    ]
