# Generated by Django 5.1.1 on 2024-10-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_app', '0002_headerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSidebarNews',
            fields=[
                ('sidebarnews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_app.sidebarnews')),
            ],
            bases=('home_app.sidebarnews',),
        ),
    ]
