# Generated by Django 5.1.1 on 2024-10-29 08:30

import shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[shop_app.models.validate_image_product]),
        ),
    ]
