# Generated by Django 5.1.1 on 2024-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_shopheaderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('social', 'Соц-сеть')], max_length=100),
        ),
    ]
