# Generated by Django 5.1.1 on 2024-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Телефон', 'Телефон'), ('Email', 'Email'), ('Соц-сеть', 'Соц-сеть')], max_length=100),
        ),
    ]
